import type {Metadata} from 'next'
import NextTopLoader from 'nextjs-toploader'
import {Theme} from "@radix-ui/themes";
import {ReactNode} from 'react'

import {Header} from "@/common/components/Header/Header";

import '@/styles/_index.scss'
import styles from './layout.module.scss'
import {AppSidebar} from "@/common/components/AppSidebar/AppSidebar";
import {SignIn} from "@/features/auth";

export const metadata: Metadata = {
    description: 'Generated by create next app',
    title: 'INC-Project',
}

export default function RootLayout({children}: { children: ReactNode }) {
    return (
        <html lang="en">
        <body>
        <NextTopLoader color={'#397df6'} showSpinner={false}/>
        {/*добавить компонент Providers*/}
        {/*<Providers>*/}
        <Theme className={styles.bodyContainer} style={{backgroundColor: 'transparent'}}>
            <Header/>
            <div className={styles.mainBody}>
                <AppSidebar/>
                <SignIn/>
                <main className={styles.main}>{children}</main>
            </div>
        </Theme>
        {/*</Providers>*/}
        </body>
        </html>
    );
}
